spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: Bakaazzedine456
    baseline-version: 0
    locations: classpath:migration
    url: jdbc:postgresql://localhost:5435/auth
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/auth
    username: postgres
    password: Bakaazzedine456