server:
  port: 8082

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      exchange: data-exchange
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: Bakaazzedine456
    baseline-version: 0
    locations: classpath:migration
    url: jdbc:postgresql://localhost:5435/auth
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/auth
    username: postgres
    password: Bakaazzedine456

jwt:
  secret-key: VGhpc1NIaXRJc1RoZVNjcmV0S2V5Rm9yV2hhdGV2ZXI=
  expiration-time: 864_000_000