server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/auth
    username: postgres
    password: Bakaazzedine456
  flyway:
    url: jdbc:postgresql://localhost:5435/auth
    user: postgres
    password: Bakaazzedine456
    locations: classpath:migration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      default-receive-queue: auth-queue
      exchange: data-exchange

# JWT Configuration
jwt:
  expiration-time: 86400000 # 24 hours in milliseconds






