server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: playbook_document

  rabbitmq:
    host: localhost
    port: 5672
    username: mongo
    password: Bakaazzedine456
    template:
      default-receive-queue: document-queue
      exchange: data-exchange