server:
  port: 8084

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: document-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      exchange: data-exchange
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: mongo
      password: Bakaazzedine456
      database: documents
