server:
  port: 8083

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: organization-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      exchange: data-exchange
  flyway:
    baseline-on-migrate: true
    enabled: true
    password: Bakaazzedine456
    user: postgres
    baseline-version: 0
    locations: classpath:migration
    url: jdbc:postgresql://localhost:5434/organizations
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/organizations
    username: postgres
    password: Bakaazzedine456