server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/organizations
    username: postgres
    password: Bakaazzedine456
  flyway:
    url: jdbc:postgresql://localhost:5434/organizations
    user: postgres
    password: Bakaazzedine456
    locations: classpath:migration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      default-receive-queue: organization-queue
      exchange: data-exchange



