spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    password: Bakaazzedine456
    user: postgres
    baseline-version: 0
    locations: classpath:migration
    url: jdbc:postgresql://localhost:5434/organizations
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/organizations
    username: postgres
    password: Bakaazzedine456