server:
  port: 8761

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: registry-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
