server:
  port: 8081

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      exchange: data-exchange
  flyway:
    baseline-on-migrate: true
    enabled: true
    password: Bakaazzedine456
    user: postgres
    baseline-version: 0
    locations: classpath:migration
    url: jdbc:postgresql://localhost:5433/users
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/users
    username: postgres
    password: Bakaazzedine456