spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/users
    username: postgres
    password: Bakaazzedine456
  flyway:
    url: jdbc:postgresql://localhost:5433/users
    user: postgres
    password: Bakaazzedine456
    locations: classpath:migration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Bakaazzedine456
    template:
      default-receive-queue: user-queue
      exchange: data-exchange

server:
  port: 8082

